feat(support): [SFEQS-1549] Add a basic Info endpoint
pagopa/io-sign pull request #107
Opened 2023-03-27 08:10 UTC by lucacavallaro

#### List of Changes

1. Add a basic `Info` endpoint that just returns 200 OK response
2. Adjust logging settings
3. Add npm-pack for deploying 

#### Motivation and Context

the Info endpoint is required for the healtcheck

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-03-27 13:23 UTC, grausof requested changes

2023-03-27 13:41 UTC, lucacavallaro commented on apps/io-func-sign-support/src/infra/http/handlers/info.ts
> +);
> Add a **BASIC** Info endpoint that just returns 200 OK response

It's written in the PR body :) I can't use the `healthcheck` functions already implemented, because they don't allow us to make a good separation between the action and the underlying infrastructure so - for now - we use this basic info endpoint that helps us to check the configuration.

In the next weeks, I'll add a new package in `io-std` to manage healthchecks in a more abstract way

2023-03-27 13:50 UTC, grausof commented on apps/io-func-sign-support/src/infra/http/handlers/info.ts
> +);
Ok then let's add a todo

2023-05-18 09:36 UTC, grausof approved these changes

2023-05-18 09:37 UTC, merged