feat (user): [SFEQS-1315] Adds support to the QTSP test environment
pagopa/io-sign pull request #109
Opened 2023-03-27 13:36 UTC by grausof

This PR adds support to the QTSP test environment therefore depending on the issuer environment it is chosen which QTSP environment to use (`TEST`/`DEFAULT`)

#### List of Changes
- Added issuer-environment parameter in `getSignatureRequest`
- Added `x-iosign-issuer-environment` header to `getQtspClauses`
- Added QTSP test environment

#### How Has This Been Tested?
Tested locally with cloud resources

#### Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-03-27 17:43 UTC, grausof commented on apps/io-func-sign-user/openapi.yaml
> +            - environment
this is a response with an added parameter. Why do you think it's a breaking change?

2023-03-28 06:06 UTC, lucacavallaro requested changes

2023-03-28 06:06 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-signature.ts
> +                ),
can you extract this conversion to base64 code in a dedicated function?

2023-03-28 07:35 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-signature.ts
> +                ),
why do you think it is necessary to write an ad-hoc function for the conversion? Perhaps it would be better to extrapolate the stringify part of the json

2023-03-28 10:17 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-signature.ts
> +                ),
I added a utility function in the @io-sign package!

2023-03-28 11:12 UTC, lucacavallaro approved these changes

2023-03-28 11:12 UTC, lucacavallaro commented on packages/io-sign/src/utility.ts
> +export const stringToBase64Encode = (arrayBuffer: string) =>
(additional tip) since you are using `Either` you can also decode the input as a string (so you can take an `unknown` as input ad avoid `undefined as unknown as string`)

2023-03-28 11:30 UTC, grausof commented on packages/io-sign/src/utility.ts
> +export const stringToBase64Encode = (arrayBuffer: string) =>
done!

2023-03-28 11:33 UTC, merged