feat: [SFEQS-1352] Add analytics event
pagopa/io-sign pull request #129
Opened 2023-04-17 08:44 UTC by grausof

Adds sending of analytics events to `datalake` eventhub (PDV).

#### List of Changes
Added the following analytics events:
-  Document uploaded 
- Document rejected
- Signature ready
- Signature send
- Notification rejected
- Signature signed
- Signature rejected
- QTSP errors

#### How Has This Been Tested?
TEsted locally

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-04-17 11:25 UTC, lucacavallaro requested changes

2023-04-17 11:25 UTC, lucacavallaro commented on apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts
> +        ),
it's not very linear, try to rewrite it using only one `createAndSendAnalyticsEvent` at the end, the only thing that changes is the event name

2023-04-17 11:25 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/validate-signature.ts
> +                )
ditto (maybe here you can use `TE.chainFirst`)

2023-04-17 15:22 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/validate-signature.ts
> +                )
Anfortunately for `Alt` there is no `TE.altFirst` lik e`TE.chainFirst` so this is the only way to do it.

2023-04-17 15:23 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts
> +        ),
it is not possible to do this as the first time is a chain while the second call is inside an Alt.

2023-04-18 14:39 UTC, lucacavallaro approved these changes

2023-04-18 17:14 UTC, merged