feat: [SFEQS-1643] Add loader dialog
pagopa/io-sign pull request #149
Opened 2023-05-08 13:34 UTC by grausof

Adds the modal (`LoaderDialog`) for loading the signature request.

2023-05-08 13:47 UTC, gunzip approved these changes

2023-05-08 13:49 UTC, silvicir approved these changes

2023-05-16 07:59 UTC, lucacavallaro requested changes

2023-05-16 07:59 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +  static get properties() {
you should use the `@property` decorator on `showCloseButton` instead of `properties` function

2023-05-16 07:59 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +          ${this.showCloseButton === "true"
here you should use the `when` directive instead of the ternary operator

```ts
when(this.showCloseButton, html`....`)
```

2023-05-16 07:59 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +            : html``}
fyi: instead of 

```ts
html``
```

you can use `nothing` imported from `lit` module

2023-05-16 07:59 UTC, lucacavallaro commented on packages/web-sdk/src/components/LoaderDialog.ts
> +        <p>${msg(html`Stiamo preparando i<br />documenti...`)}</p>
where is the localized data?

2023-05-16 07:59 UTC, lucacavallaro commented on packages/web-sdk/src/io-sign.ts
> +      const IOLink = new URL(
please keep the 
```
// TODO(SFEQS-1646): replace this hardcoded base url with a dynamic one
```

the `/fci/main` part should be fetched from io-link service and should not be hardcoded

2023-05-16 08:21 UTC, lucacavallaro requested changes

2023-05-16 08:26 UTC, grausof commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
Because it is an attribute. 

> Note, some primitive values are handled specially in attributes. Boolean values are converted to strings so, for example, false renders 'false'. Both undefined and null render to an attribute as an empty string.

2023-05-16 08:43 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
sure! but (1) note that in the JavaScript code you don't use the `attribute` value directly, ma the `property` computed from an attribute (so you can parse attribute - that are always strings - targeting the appropriate type, `boolean` in this case)
- ref 1 https://gomakethings.com/the-difference-between-attributes-and-properties-in-vanilla-js
- ref 2 https://lit.dev/docs/components/properties/#conversion-type

(2) note how HTML works! Although attributes can only be strings, Boolean attributes have always been present in HTML. Think of the `disabled` attribute of button or input (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled), if the attribute is present the `disabled` property is `true`, if not it's `false`

---

the default (attribute -> property) converter of `Lit` supports `boolean` attributes (see the table here https://lit.dev/docs/components/properties/#conversion-type) so you should refactor you code to use `Boolean` as `@property` type and simply add (or omit) the attribute in the DOM.

2023-05-16 09:01 UTC, grausof commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
Ok thanks, it didn't work for me because I set the default to true. 

> For a boolean property to be configurable from an attribute, it must default to false. If it defaults to true, you cannot set it to false from markup, since the presence of the attribute, with or without a value, equates to true. This is the standard behavior for attributes in the web platform.

2023-05-16 09:14 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
Since the default action should be "show the close button" you must "invert" the logic :)

2023-05-16 09:48 UTC, grausof commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
The logic is correct. The additional attribute is `with-close-button` which if present sets `withCloseButton` to true otherwise it is false

2023-05-16 09:58 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
(at the moment the click on the backdrop closes the dialog... is this disabled when the close button is not rendered?)

2023-05-16 10:03 UTC, grausof commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
okay right. I reversed the logic. Yes, the click on the backdrop is disabled!

2023-05-16 10:07 UTC, lucacavallaro commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
(don't kill me!) since the property has effect on the behaviour (dialog can be closable or not) and not only on the rendering of the "close button" - the attribute should have a more appropriate (explicit) name

2023-05-16 10:09 UTC, grausof commented on packages/web-sdk/src/components/Dialog.ts
> +            this.showCloseButton === "true",
`closable` could be a good attribute?

2023-05-16 10:47 UTC, merged