feat(backoffice): [SFEQS-1865] Create api key endpoint - back office
pagopa/io-sign pull request #182
Opened 2023-07-13 12:49 UTC by silvicir

#### List of Changes
1. Added `api/api-keys` route `POST` method to create an api key
2. Added unit tests

#### Motivation and Context
To run the application, you have to execute `az login` first

#### How Has This Been Tested?

Trough unit tests with `vitest`.

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-26 09:55 UTC, lucacavallaro requested changes

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/.env
> +PRODUCT_NAME=# override this variable in .env.local
what is the purpose of this variable?

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/.env
> +RESOURCE_GROUP_NAME=# override this variable in .env.local
can you give a proper prefix to each variable?

ex. `AZURE_` or `COSMOS_`

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/apim.ts
> +export const getApimClient = () => {
you should wrap these kind of functions with `cache` function from `react`

in this way you can avoid the top-level `apimClient` variable

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/lib/error.ts
> +export class ParsingInputError extends Error {
imho we can use just `ZodError` for parsing/validation error

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/route.ts
> +}
imho we can manage the response in a more explicit/plain way

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +}
I think that this function should manage the sync errors (getApimClient and getApimConfig)

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +      })
imho we should not mix `then` with `async/await` 

can you try to refactor it using only then or only async/await?

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +import { id as newId } from "@io-sign/io-sign/id";
I suggest you to use directly the `ulid` lib instead of `@io-sign/io-sign`

`@io-sign/io-sign` is a big library that makes sense only if it used extensively across the project

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +  name: z.string().nonempty(),
what is the difference between `name` and `displayName`?

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +  displayName: z.string().nonempty(),
`displayName` should have a default value, random-generated

2023-07-26 09:55 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +const newApiKey = (apiKey: ApiKeyBody): ApiKey => ({
(don't kill me!) I think that we should align with standard javascript constructors that are `PascalCased` and without any `prefix`

so this function can be renamed `ApiKey` (like `Number`, `Date` or `Boolean`)

2023-07-26 11:56 UTC, silvicir commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +const newApiKey = (apiKey: ApiKeyBody): ApiKey => ({
all right. btw it is similar to the other constructors in `io-sign` like `newDossier` or `newSignatureRequest`

2023-07-26 12:12 UTC, silvicir commented on apps/io-sign-backoffice-ca/.env
> +PRODUCT_NAME=# override this variable in .env.local
as you can see the subscriptions on Azure are associated with a product scope

2023-07-26 12:21 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +const newApiKey = (apiKey: ApiKeyBody): ApiKey => ({
@silvicir yes I know! but I think that I made a mistake on `io-sign` :)

2023-07-26 12:27 UTC, silvicir commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +  displayName: z.string().nonempty(),
we agreed that `displayName` should be generated front-end side

2023-07-31 09:33 UTC, lucacavallaro requested changes

2023-07-31 09:33 UTC, lucacavallaro commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +}
1. Is `readApiKey` really necessary? that is the behaviour of `createApimSubscription` and `insertApiKey` on duplicate input?
2. Imho `readApiKey` (in the case if it's really needed) should be named `getApiKey` and should take only `displayName` and `institutionId` parameters! we should not allow the same displayName in different environments
3. What happen if `createApimSubscription` succeed and `insertApiKey` fails? maybe we should run a "cleanup" job that deletes the api key 
4. I'm thinking we can remove `resourceId` and use just the `id` of `ApiKey` - what do you think?

2023-07-31 10:01 UTC, silvicir commented on apps/io-sign-backoffice-ca/src/app/api/api-keys/_lib/api-key.ts
> +}
Right now this is the input:
```
{
    "institutionId": "a0e07d4a-9792-4af3-8175-889aead727b8",
    "displayName": "Comune di C",
    "environment": "DEFAULT",
    "resourceId": "178909225251"
}
```
on duplicated input `createApimSubscription` will not create a new subscription while `insertApiKey` will create a new item.

2023-07-31 15:47 UTC, lucacavallaro approved these changes

2023-07-31 15:55 UTC, merged