feat: Create filled document [SFEQS-1131, SFEQS-1111]
pagopa/io-sign pull request #21
Opened 2022-11-24 16:54 UTC by grausof

This PR implements the createFilledDocument endpoint. 
Also adds:
- The PDF infrastructure for filling out forms
- Upload to blob storage

#### How Has This Been Tested?
Tested in simulator

#### Types of changes
- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2022-11-24 17:01 UTC, lucacavallaro requested changes

2022-11-24 17:01 UTC, lucacavallaro commented on packages/io-sign/src/infra/pdf.ts
> +import { PDFDocument, PDFForm } from "pdf-lib";
Maybe we can move this module in a dedicated package? Such as "@internal/pdf-something"?

2022-11-24 17:01 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +type Fields = [NameField, FamilyNameField, EmailField, FiscalCodeField];
Why are you using a fixed-size liet instead of a Record?

2022-11-24 19:37 UTC, lucacavallaro requested changes

2022-11-24 19:37 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +        const httpApiFetch = agent.getHttpFetch(process.env);
"process.env" must be accessed only from "infrastructure" layer

This agent should be passed via fn arguments

2022-11-25 00:00 UTC, gunzip requested changes

2022-11-25 00:02 UTC, gunzip commented on apps/io-func-sign-user/openapi.yaml
> +          name: signer_id
```suggestion
          name: x-iosign-signer-id
```

2022-11-25 08:10 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/cosmos/errors.ts
> +import { CosmosErrors } from "@pagopa/io-functions-commons/dist/src/utils/cosmosdb_model";
ok, I'll do it!

2022-11-25 08:11 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/functions/create-filled-document.ts
> +/* TODO: This function will have to be asynchronous.
I converted it to DRAFT to add this implementation!

2022-11-25 08:12 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +type Fields = [NameField, FamilyNameField, EmailField, FiscalCodeField];
there must be only those 4 values in the array!

2022-11-25 08:38 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +        const httpApiFetch = agent.getHttpFetch(process.env);
`agent.getHttpFetch` comes from  "@pagopa/ts-commons" and the signature is: `getHttpFetch: (env: NodeJS.ProcessEnv, extraOptions?: agentkeepalive.HttpOptions) => typeof fetch`

I will pass the whole configured  fetch as an argument!

2022-11-25 10:24 UTC, grausof commented on apps/io-func-sign-user/openapi.yaml
> +      x-import: "@pagopa/ts-commons/lib/strings"
so we will have to change also on the issuer openapi? @lucacavallaro

2022-11-25 10:28 UTC, lucacavallaro commented on apps/io-func-sign-user/openapi.yaml
> +      x-import: "@pagopa/ts-commons/lib/strings"
@gunzip why you suggest to remove this import? this will probably break our "api layer"

2022-11-25 10:30 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +        const httpApiFetch = agent.getHttpFetch(process.env);
here you should use the same pattern adopted in the rest of the codebase: port & adapters

-> a `type` that represent this operation, declared in domain and used in `use-case` and a concrete implementation in `infra` with the configured `fetch`

2022-11-25 10:32 UTC, gunzip commented on apps/io-func-sign-user/openapi.yaml
> +      x-import: "@pagopa/ts-commons/lib/strings"
if you use `minLenght: 1` it's automatically imported

2022-11-25 10:34 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/cosmos/errors.ts
> +      // TODO: show details about validation
This file derives from the package Issuer. I think we will have to do a review of all the TODOs later and fix the things that are wrong!

2022-11-25 10:46 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +type FamilyNameField = Field & { fieldName: "surname" };
I used family_name as it does in the rest of IO. surname in this case is just a mock but it might change according to the module provided by the QTSP. Could also be "cognome"

2022-11-25 11:48 UTC, gunzip requested changes

2022-11-25 11:48 UTC, gunzip commented on apps/io-func-sign-user/src/infra/http/fetch-timeout.ts
> +export const makeFetchWithTimeout = (
I suggest to use another argument for `makeFetchWithTimeout` which default to `process.env` (this facilitate testing). Generally, avoid inner access to global variables.

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/FillDocument/function.json
> +  "scriptFile": "../dist/fill-document.js",
I'd rename this to `CreateFilledDocument` which is the name used into API specs

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/FillDocument/function.json
> +        "delayInterval": "00:00:10"
```suggestion
        "delayInterval": "00:00:5"
```

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/openapi.yaml
> +      x-import: "@pagopa/ts-commons/lib/strings"
```suggestion
```

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
So why it's called 'makeCreateFilledDocument'?

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
```suggestion
/** Create and return the storage path (URL) for the ToS document.
 *
 * The caller of this API is expected to poll on it since the endpoint will return 404 until the ToS document gets processed.
```

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> + * It also writes on a queue the information necessary to start the module creation function via the trigger queue
```suggestion
```

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/fill-document.ts
> +// This function downloads the pdf form, compiles it and uploads it to blobStorage
```suggestion
/** Downloads the ToS pdf form, compiles and stores the filled document.
```

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/fill-document.ts
> +// This function downloads the pdf form, compiles it and uploads it to blobStorage
Do not leak implementaion details (blobSorage) since they're subject to changes. Moreover, use `/** */` for methods documentation and `//` for inline comments.

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/fill-document.ts
> +          TE.chain((buffer) => pipe(fields, populatePdf(buffer))),
If you invert arguments in `populatePdf` this may become 

```suggestion
          TE.chain(populatePdf(fields)),
```

as a general rule you should put configuration arguments (ie. `fields`) at first, then  data arguments (`buffer`) at last.

2022-11-27 21:29 UTC, gunzip commented on apps/io-func-sign-user/src/infra/azure/functions/fill-document.ts
> +const filledContainerClient = new ContainerClient(
consider that these clients must be singletons (so maybe it's worth to extract it into another module in order to be shared by functions?)

2022-11-27 21:29 UTC, gunzip commented on packages/pdf-handler/src/pdf.ts
> + * pdfFields and return the filled pdf in base64 */
this is clear reading the code and can be removed
```suggestion
```

2022-11-27 21:29 UTC, gunzip commented on packages/pdv-tokenizer/src/signer.ts
> +                    `An error occurred to retrieve the fiscal code from the signerId`
```suggestion
                    `The attempt to get signer's fiscal code from its identifier failed.`
```

2022-11-28 08:43 UTC, grausof commented on apps/io-func-sign-user/FillDocument/function.json
> +  "scriptFile": "../dist/fill-document.js",
`CreateFilledDocument` exists and is the function that takes care of the implementation of the openapi specification. `FillDocument` is the function that is triggered by a queue to fill the PDF fields.

2022-11-28 08:46 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/fill-document.ts
> +          TE.chain((buffer) => pipe(fields, populatePdf(buffer))),
https://kyleshevlin.com/just-enough-fp-argument-order

2022-11-28 08:50 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/fill-document.ts
> +          TE.chain((buffer) => pipe(fields, populatePdf(buffer))),
OK thank you. I will try in the future!

2022-11-28 08:57 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/functions/fill-document.ts
> +const filledContainerClient = new ContainerClient(
Yes I agree. It was done this way as for the whole codebase. I saw that there is a dedicated PR so let's fix it apart.

2022-11-28 09:16 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
throughout the codebase it was used as a convention to prepend `make` to the function name of the use case.

2022-11-28 09:36 UTC, gunzip approved these changes

2022-11-28 09:40 UTC, lucacavallaro approved these changes

2022-11-28 09:45 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
right now we are using this naming convention

`new` prefix for "record" constructors -> `newSignatureRequest`, `newSigner`, `newIssuer`
`make` prefix for handler/use-case constructors/adapter constructors -> `makeGetSignatureRequest`

maybe in the future we can adopt `new` as prefix for all kind of constructors

2022-11-28 09:46 UTC, gunzip commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
I ain't asking about the "make" parte but the "CreateFilledDocument" since looking at the comment it seems that this method does not create a filled document.

2022-11-28 09:57 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-filled-document.ts
> +/* This function returns only the callback url of the filled document without creating it.
yes, I renamed it to: `makeCreateFilledDocumentUrl`

2022-11-28 10:11 UTC, manuelcoppotelli commented
Depends on pagopa/io-infra#305

2022-11-28 11:09 UTC, merged