[SFEQS-2023] Add io-sign-backoffice-func
pagopa/io-sign pull request #221
Opened 2023-10-05 10:46 UTC by silvicir

#### List of Changes

1. Created `io-sign-backoffice-func` directory
2. Added `onSelfcareContractsMessage` function with Event Hubs trigger

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-05 13:36 UTC, lucacavallaro requested changes

2023-10-05 13:36 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/package.json
> +    "start": "func start"
can you add here `prettier` and `eslint` ? this package json should contain `lint`, `lint:fix` and `format` script

2023-10-06 07:08 UTC, gunzip commented
can we add a readme with the setup to make this run locally and the description of the function?

2023-10-06 07:33 UTC, silvicir commented
> can we add a readme with the setup to make this run locally and the description of the function?

Then we should add a readme for all the functions. The command is just `yarn run start` so maybe we could update the `io-sign` README.

2023-10-06 11:15 UTC, gunzip commented
It's ok to put this information where we can find all the descriptions, one for each function.

2023-10-09 08:13 UTC, lucacavallaro commented
> can we add a readme with the setup to make this run locally and the description of the function?

I think this approach can lead us to bad practices and poor documentaiton.

The instructions to run the project locally are (and must be!) the same for all the workspaces. 

In particular, each workspace must have its own `build`, `start`, `format` and `lint` script. No workspace should have exceptions and different ways of working.

Maybe we should update the `README` to enforce this pattern and remove all the references to specific workspaces.

2023-10-09 08:36 UTC, merged