chore(bo): [SFEQS-2025] Migrate issuer onboarding slack message
pagopa/io-sign pull request #237
Opened 2023-10-30 08:01 UTC by silvicir

#### List of Changes

When a new institution onboards, the function `CreateIssuer` on `io-func-sign-issuer` gets triggered and a slack message is sent. We wanted to move this logic in the back office domain

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-30 10:42 UTC, lucacavallaro requested changes

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/app/main.ts
> +const config = configOrError;
I would remove fp-ts code here, since this portion of code throws.
imho it can be just a zod parse

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/app/main.ts
> +);
these repositories can be composed in one `BackofficeApiClient` class

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/app/main.ts
> +const slackRepository = new SlackMessageRepository(config.slack.webhookUrl);
I would replace this class with just a `sendSlackMessage` function (maybe we can reuse the backoffice one?)

to me it's an overkill defining a class just for one operation

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/back-office/config.ts
it can be replaced entirely by zod, I don't see advantages of `fp-ts` here (but I know why you implemented it in this way)

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/back-office/issuer.ts
> +});
if this schema must be identical to the backoffice one, move it to `@io-sign/io-sign`

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/handlers/__test__/on-selfcare-contracts-message.spec.ts
> +  let slackRepository: SlackRepository;
use `vitest` [context](https://vitest.dev/guide/test-context.html) instead of `describe-scoped` variable

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/handlers/handler-kit/handler-kit-azure-func.ts
this file should be moved to `pagopa/io-std`

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/handlers/health.ts
> +  return { status: 200 };
empty body = `204`

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
to me this file can be simplified, we really need `baseContract` ? I think we can keep only a `contractScheme` scheme with the `io-sign` contract

2023-10-30 10:42 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/selfcare/use-cases.ts
> +export const getSupportEmail =
`supportEmail` must be read only from `issuer`

the `supportEmail` in institution it's not reliable, because it can't be updated

2023-10-30 13:54 UTC, silvicir commented on apps/io-sign-backoffice-func/src/infra/selfcare/use-cases.ts
> +export const getSupportEmail =
we only have this `supportEmail` at this stage
btw it is just an onboarding message, it is not supposed to be reliable

2023-11-01 22:30 UTC, gunzip commented on apps/io-sign-backoffice-app/src/app/api/api-keys/[api-key]/route.ts
> +  "api-key": z.string().min(1),
why this change?

2023-11-01 22:30 UTC, gunzip commented on apps/io-sign-backoffice-func/src/infra/selfcare/use-cases.ts
> +      institutionRepository.getById.bind(institutionRepository),
```suggestion
      institutionRepository.getById(internalInstitutionId),
```

2023-11-01 22:30 UTC, gunzip commented on apps/io-sign-backoffice-func/src/infra/slack/message.ts
> +          fetch(this.#webhookUrl, {
all those fetches should have a timeout (and use keepalive ideally, see https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#cause)

2023-11-02 10:03 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/selfcare/use-cases.ts
> +export const getSupportEmail =
we don't need to have `supportEmail` in the message (we don't use it), so can be removed at all

2024-02-05 11:12 UTC, lucacavallaro requested changes

2024-02-05 11:12 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
> +const contract = z.object({
I saw that you made a discriminated union on `state` (`ioSignContracts` schema) but is this necessary? maybe `contractSchema` alone is enough

2024-02-05 11:12 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/slack/issuer-message.ts
> +    vatNumber: \`${vatNumber}\`\n`;
here you can use the same "format" as newer slack messages sent by the backoffice

something like

> (_backoffice_) __DESCRIPTION__ (`INSTITUTION_ID`) ha effettuato l'onboarding.

2024-02-05 11:12 UTC, lucacavallaro commented on packages/io-sign/src/issuer.ts
> +});
maybe this schema can be shared

2024-02-05 11:12 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/http/fetch.ts
> +export const fetchWithTimeoutAndKeepAlive = (
instead a new `fetch` wrapper, I would export only the configured dispatcher

so when I need this config I can use in this way `fetch(url, { dispatcher, .... }`

2024-02-05 11:12 UTC, lucacavallaro commented on apps/io-sign-backoffice-func/src/infra/slack/use-cases.ts
> +    sendMessage(message);
I think we can use directly the `sendMessage` function from the `message` module

2024-02-05 11:17 UTC, silvicir commented on packages/io-sign/src/issuer.ts
> +});
what do you mean?

2024-02-05 15:44 UTC, silvicir commented on apps/io-sign-backoffice-func/src/app/main.ts
> +const { backOffice, slack, selfcare } = getConfigFromEnvironment();
an error is thrown

2024-02-06 09:39 UTC, silvicir commented on apps/io-sign-backoffice-func/src/infra/selfcare/contract.ts
> +const contract = z.object({
I used a discriminated union so I could use the type guard `isActive`

2024-02-07 11:45 UTC, lucacavallaro approved these changes

2024-02-08 13:46 UTC, merged