[EC-318] Migrated pipelines & terraform code from io-infra
pagopa/io-sign pull request #300
Opened 2024-06-20 15:54 UTC by mamu0

#### List of Changes

With this PR, the entire Terraform infrastructure, previously located in the io-infra repository, has been moved to the infra/prod folder. Additionally, two GitHub Actions pipelines have been created to manage the CI/CD flow. One pipeline executes the Terraform plan and is triggered when a PR is created, and the other pipeline performs the Terraform apply and is triggered when the PR is merged.

#### Motivation and Context

This PR completes the migration plan for the pipelines within io-infra. By doing so, the code specific to io-sign has been moved from io-infra to its dedicated repository. This ensures that all code is maintained in the same place as the rest of the project.

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-28 14:15 UTC, Krusty93 commented on infra/identity/prod/locals.tf
> +    Source      ="https://github.com/pagopa/io-sign/blob/main/src/identity/prod" # "https://github.com/pagopa/dx-typescript/blob/main/infra/identity/prod/westeurope" #
```suggestion
    Source      = "https://github.com/pagopa/io-sign/blob/main/src/identity/prod"
```

Do not forget to run `terraform fmt -r`

2024-06-28 14:15 UTC, Krusty93 commented on infra/identity/prod/main.tf
> +      version = "<= 3.100.0"
```suggestion
      version = "<= 3.108.0"
```

2024-06-28 14:16 UTC, Krusty93 commented on infra/identity/prod/main.tf
> +      subscription = [
Where these values have been taken from?

2024-06-28 14:23 UTC, Krusty93 commented on infra/identity/prod/main.tf
> +  domain    = "${local.domain}-infra"
I know it's ok and this code works, however I suggest to remove `-infra` as it intended as default by non-written convention

2024-06-28 14:23 UTC, Krusty93 commented on infra/repository/data.tf
> +  name                = "${local.project}-sign-infra-github-ci-identity"
ditto

2024-06-28 14:23 UTC, Krusty93 commented on infra/repository/data.tf
> +  name                = "${local.project}-sign-infra-github-cd-identity"
ditto

2024-06-28 14:24 UTC, Krusty93 commented on infra/repository/github_repository.tf
> +resource "github_repository" "this" {
Is this imported into the state?

2024-06-28 14:31 UTC, Krusty93 commented on infra/resources/prod/terraform.tfvars
> +container_app_environment = {
I think this should be removed

2024-06-28 14:31 UTC, Krusty93 commented on infra/resources/prod/github_runner.tf
> +data "azurerm_key_vault" "key_vault_common" {
I think this should be removed. Create a new Terraform config like [this](https://github.com/pagopa/dx-typescript/tree/main/infra/github-runner/prod/westeurope) instead

2024-07-01 07:55 UTC, Krusty93 requested changes
I suggest few changes I detailed in comments

2024-07-02 14:40 UTC, mamu0 commented on infra/identity/prod/main.tf
> +      subscription = [
This is a copy from io-infra configuration, but maybe we can decide to remove some roles to obtain Least Privilage

2024-07-02 14:42 UTC, mamu0 commented on infra/identity/prod/main.tf
> +  domain    = "${local.domain}-infra"
The `-infra` is needed because now exist and old identity that have the same name, so in this way we don't have a conflict. 
But i think we need to rename or remove the old one and then use the right name for this identity.

2024-07-02 14:43 UTC, mamu0 commented on infra/repository/github_repository.tf
> +resource "github_repository" "this" {
Yes, and also applied for the variables

2024-07-02 14:45 UTC, mamu0 commented on infra/resources/prod/terraform.tfvars
> +container_app_environment = {
I believe we need to carefully evaluate because it is part of the old configuration in io-infra. It has not been modified to avoid causing disruptions with the currently deployed architecture.

2024-07-02 14:59 UTC, Krusty93 commented on infra/resources/prod/terraform.tfvars
> +container_app_environment = {
I see your point and is correct, but nobody's touching this repo for months. So we can easily make all required changes with no rush (~ 2h even though task itself is quick)

2024-08-30 14:52 UTC, Krusty93 requested changes

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-backoffice-app.yaml
> +    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
Is this workflow correct?

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-backoffice-app.yaml
> +      environment: webapp-prod-cd
```suggestion
      environment: webapp-prod
```

`cd` is appended by the template

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-backoffice-func.yaml
> +      environment: webapp-prod-cd
```suggestion
      environment: webapp-prod
```

`cd` is appended by the template

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-issuer-func.yaml
> +      environment: webapp-prod-cd
```suggestion
      environment: webapp-prod
```

`cd` is appended by the template

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-support-func.yaml
> +      environment: webapp-prod-cd
```suggestion
      environment: webapp-prod
```

`cd` is appended by the template

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/deploy-user-func.yaml
> +      environment: webapp-prod-cd
```suggestion
      environment: webapp-prod
```

`cd` is appended by the template

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/opex_api_issuer.yaml
> +          tenant-id: ${{ secrets.ARM_TENANT_ID }}
These should be escaped using a env var

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/opex_api_support.yaml
> +          tenant-id: ${{ secrets.ARM_TENANT_ID }}
ditto

2024-08-30 14:52 UTC, Krusty93 commented on .github/workflows/opex_api_user.yaml
> +          tenant-id: ${{ secrets.ARM_TENANT_ID }}
ditto

2024-08-30 14:52 UTC, Krusty93 commented on .identity/identity_opex.tf
> +# module "opex_identity_ci" {
Why not deleting it?

2024-08-30 14:52 UTC, Krusty93 commented on .identity/identity_web_apps.tf
> +# module "web_apps_identity_cd" {
ditto

2024-08-30 14:52 UTC, Krusty93 commented on .pre-commit-config.yaml
> +      - id: terraform_validate
Add
`exclude: '(\/_?modules\/.*)'`

2024-08-30 14:52 UTC, Krusty93 commented on CODEOWNERS
> +@lucacavallaro @grausof
```suggestion
* @lucacavallaro @grausof
```

2024-08-30 14:52 UTC, Krusty93 commented on infra/github-runner/prod/locals.tf
> +    Owner       = "IO"
Add
`Management Team = "IO Firma"`

2024-08-30 14:52 UTC, Krusty93 commented on infra/identity/prod/README.md
> +# DX - GitHub federated Managed Identities
```suggestion
# IO Sign - GitHub federated Managed Identities
```

2024-08-30 14:52 UTC, Krusty93 commented on infra/identity/prod/locals.tf
> +  location  = "westeurope"
```suggestion
```

2024-08-30 14:52 UTC, Krusty93 commented on infra/identity/prod/locals.tf
> +    Owner       = "IO"
ditto

2024-08-30 14:52 UTC, Krusty93 commented on infra/repository/README.md
> +# IO Infra - Repository
```suggestion
# IO Sign - Repository
```

2024-08-30 14:52 UTC, Krusty93 commented on infra/identity/prod/main.tf
> +  env       = "app-${local.env}"
`app` or `webapp`? we generally use `app`

2024-08-30 14:52 UTC, Krusty93 commented on infra/repository/github_environment_cd.tf
> +  environment = "webapp-prod-cd"
ditto

2024-08-30 15:02 UTC, mamu0 commented on .github/workflows/deploy-backoffice-app.yaml
> +    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
This is the one used before [deploy-workspace.yaml](https://github.com/pagopa/io-std/blob/main/.github/workflows/deploy-workspace.yaml), it seems to be similar

2024-08-30 15:20 UTC, mamu0 commented on infra/repository/github_environment_cd.tf
> +  environment = "webapp-prod-cd"
since it was defined as `webapp` I left it, but if `app` is the standard we can change it

2024-09-02 09:42 UTC, Krusty93 commented on infra/identity/prod/main.tf
> +          "Contributor",
Is this role needed?

2024-09-02 10:01 UTC, lucacavallaro commented on .github/workflows/deploy-backoffice-app.yaml
> +    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
from now on we should use `web_app_deploy` instead `function_app_deploy`

(function_app_deploy will be removed soon)

2024-09-02 10:02 UTC, mamu0 commented on infra/identity/prod/main.tf
> +          "Contributor",
I don't know exactly why is used, but in the original `.identity` folder is configured in this way [link](https://github.com/pagopa/io-sign/blob/ee95df3e55ad9973fb8312f2c49457d503597441/.identity/env/prod/terraform.tfvars#L39)

2024-09-02 10:05 UTC, mamu0 commented on .github/workflows/opex_api_issuer.yaml
> +          tenant-id: ${{ env.ARM_TENANT_ID }}
a few lines below :laughing:

2024-09-03 08:38 UTC, gunzip commented on infra/resources/prod/apim_v2.tf
> +data "http" "backoffice_openapi" {
since the file is now contained in this repository you don't need to access it using the data URL anymore, you can just get file content using terraform file()

2024-09-03 08:40 UTC, gunzip commented on infra/resources/prod/apim_v2.tf
> +  content_value  = data.http.backoffice_openapi.body
```suggestion
  content_value  = file("../../apps/io-sign-backoffice-func/openapi.yaml")
```

I haven't checked the path.

2024-09-03 09:04 UTC, Krusty93 approved these changes

2024-09-03 09:08 UTC, merged