feat(user): [SFEQS-1128] Add QTSP client and implement getQtspClauses
pagopa/io-sign pull request #35
Opened 2022-12-01 16:45 UTC by grausof

This PR adds the client for the QTSP and implements the first getQtspClauses endpoint!

#### How Has This Been Tested?
Tested in local 

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2022-12-01 16:56 UTC, gunzip commented on apps/io-func-sign-user/src/infra/qtsp/client.ts
> +                `An error occurred to retrieve the auth token from QTSP | ${response.status}`
```suggestion
                `The attempt to retrieve the the auth token from the QTSP failed: ${response.status}`
```

2022-12-01 16:56 UTC, gunzip commented on apps/io-func-sign-user/src/infra/qtsp/config.ts
> +  requestTimeout: t.number,
```suggestion
  requestTimeoutMs: t.number,
```

2022-12-01 16:56 UTC, gunzip commented on apps/io-func-sign-user/src/infra/qtsp/config.ts
> +  requestTimeout: t.number,
always put unit of measure in variable names

2022-12-01 16:57 UTC, gunzip commented on apps/io-func-sign-user/src/infra/qtsp/config.ts
> +  requestTimeout: RE.right(10000),
```suggestion
  requestTimeout: RE.right(5000),
```

2022-12-01 23:00 UTC, gunzip commented
see https://github.com/pagopa/io-sign/pull/36

2022-12-02 00:06 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/qtsp/config.ts
> +  requestTimeout: t.number,
maybe in the future we can encode this information at type level: `requestTimeout: Millisecond` instead of `requestTimeout: number`

2022-12-02 09:57 UTC, gunzip approved these changes
lgtm

2022-12-02 10:10 UTC, lucacavallaro requested changes

2022-12-02 10:10 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/namirial/client.ts
> +      TE.chain((response) => TE.tryCatch(() => response.json(), E.toError)),
we should keep our code DRY

not urgent, but there is a way to avoid the repetition of `filterOrElse(isSuccessful) -> response.json()` for each call?

2022-12-02 10:16 UTC, grausof commented on apps/io-func-sign-user/src/infra/namirial/client.ts
> +      TE.chain((response) => TE.tryCatch(() => response.json(), E.toError)),
https://github.com/pagopa/io-sign/pull/36#discussion_r1037930912

2022-12-02 10:18 UTC, lucacavallaro approved these changes

2022-12-02 10:31 UTC, merged