feat!: [SFEQS-1204. SFEQS-1214] Implement functions: CreateSignatureRequest, GetSignatureRequest, MarkAsWaitForSignature
pagopa/io-sign pull request #45
Opened 2022-12-07 22:58 UTC by lucacavallaro

#### List of Changes

In `@io-sign/io-sign`:
1. Implemented new common structures (`SignatureRequest`, `Issuer`)
2. Add utilities to work with Azure blob and queues

In `io-func-sign-user`:
1. Implement `CreateSignatureRequest`, `GetSignatureRequest` Azure Functions
4. Implement `Signature Request` entity
5. Add `SAS Url` generation to make `documents` readable from mobile app
6. Add an event emitter (backed by a `Storage Queue`) to notify the changed status of a Signature Request
7. Add a function to convert `io-func-sign-issuer`'s `Signature Field` attributes to the user's one

In `io-func-sign-issuer`:
1. Implement `MarkAsWaitForSignature` Azure Function to update the `Signature Request` status when persisted on `io-func-sign-user` backend
2. Refactor `Signature Request` to enhance type safety (now is a sum type)

#### How Has This Been Tested?

It was e2e tested manually in local and development (remote) environment.

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2022-12-08 21:51 UTC, grausof requested changes

2022-12-08 21:51 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/send-notification.ts
> +                  "The tax code associated with this signer is not valid!"
```suggestion
                  "The fiscal code associated with this signer is not valid!"
```

2022-12-08 21:51 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/functions/get-signature-request.ts
> +          withExpireInMinutes(5)
Is 5 enough?

2022-12-08 21:51 UTC, grausof commented on apps/io-func-sign-user/src/signature-field.ts
> +});
Here it is also necessary to change the reference system. On the issuer side the zero point is at the top left while on the user side it is at the bottom left. You need to read the document via pdf-handler and calculate the page height. We can also do this with a separate PR but we need to enter a TODO

2022-12-08 21:51 UTC, grausof commented on apps/io-func-sign-user/src/infra/http/encoders/signature-field.ts
> +        })
I would move this part before saving the signature request on the DB in such a way as to save it already with the modified coordinates. Based on the previous comment the calculation may take some time.

2022-12-08 21:52 UTC, grausof commented on apps/io-func-sign-user/src/signature-field.ts
> +    y: coordinates.y + size.h.valueOf(),
`+` causes the code review pipeline to fail.

2022-12-08 22:06 UTC, lucacavallaro commented on apps/io-func-sign-user/src/signature-field.ts
> +});
Ok, I totally missed this! 

I'll split the task again. And you are right: if there is an async computation we have to store the result in the DB. 

Maybe we can store this kind of information (for example the document height) at "ValidateDocument" step.

2022-12-09 07:36 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/azure/functions/get-signature-request.ts
> +          withExpireInMinutes(5)
I think 5 minutes is enough, if not too much.

If you think about it, the app downloads PDFs immediately after making this HTTP call. It could also be set to 1 minute.

2022-12-09 12:05 UTC, grausof commented on apps/io-func-sign-user/extensions.csproj
> +</Project>
Is there a need to commit it?

2022-12-09 12:05 UTC, grausof commented on apps/io-func-sign-user/openapi.yaml
> +        - updated_at
```suggestion
        - id
        - status
        - dossier_id
        - signer_id
        - expires_at
        - documents
        - created_at
        - updated_at
```

2022-12-09 12:09 UTC, lucacavallaro commented on apps/io-func-sign-user/extensions.csproj
> +</Project>
yes

2022-12-09 14:31 UTC, grausof approved these changes
LGTM 🎉

2022-12-09 14:36 UTC, merged