feat!: [SFEQS-1266, SFEQS-1216] Add signatureFields validation with document metadata
pagopa/io-sign pull request #66
Opened 2023-01-17 12:04 UTC by grausof

⚠ **BREAKING CHANGE:** Added `formFields` attribute to `DocumentMetadata` in `io-sign` package!
(Previously generated signing requests are not compatible with this version!)

This PR add the `signatureFields` validation with document metadata, in detail, carry out the following checks:

- Check that the uploaded file is a PDF
- Check that in the case of _signature fields_, they are present in the PDF (check on the `fieldId`)
- Check the type of signature field that is compatible with the _PADeS_ signature
- Check that in case of coordinates the page number exists inside the PDF
- Check that in the case of coordinates, the box is inside the pdf page.

Furthermore, this PR solves a TODO [SFEQS-1216] by removing the dependencies from `infra` within the use case.

#### How Has This Been Tested?
Tested locally with cloud resources

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +        SignatureFieldAttributes.is(attributes)
Is it's possibile I would break this method into smaller ones to increase readability (you can better graps what's happening when using method names)

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +              A.filter((p) => p.number === attributes.page),
You may consider to alias these conditions (ie. `hasSomething` / `isSomething`) as well

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                attributes.coordinates.x + attributes.size.w < page.width &&
ditto

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                    pipe(validationResults.left, A.isEmpty)
It's hard to understand what's happening here, same considerations as above (or add a comment)

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                    "The specified document does not exists."
```suggestion
                    "No document was found with the specified document id."
```

2023-01-17 12:26 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +        upsertUploadMetadata({
I'd alias this method as well (ie. `markAsReady`)

2023-01-17 14:33 UTC, gunzip requested changes

2023-01-17 14:33 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                    pipe(validationResults.left, A.isEmpty)
lacks unit tests

2023-01-17 14:33 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
add unit tests

2023-01-17 15:08 UTC, lucacavallaro requested changes

2023-01-17 15:08 UTC, lucacavallaro commented on packages/io-sign/src/document.ts
> +}
1. use a `union type` instead of an `enum`
2. avoid using "suffix" such as `Enum`, put directly the name of the type (`FormFieldType`)

```suggestion
export type FormFieldType = "SIGNATURE" | "OTHER"; 
```

moreover, if the only value allowed in our case is "SIGNATURE" make sure that a different value is never accepted at the outset (traces "OTHER" only if we do something with it later)

2023-01-17 15:08 UTC, lucacavallaro commented on packages/io-sign/src/document.ts
> +          updateMetadataPageAndFields(
if `pages` and `formFields` must always be updated together, try to extract them as a single `value object` (`PDFDocument`)

2023-01-17 15:08 UTC, lucacavallaro commented on packages/io-sign/src/infra/pdf.ts
> +    fields: t.array(
I think this module can be treated like an "adapter", maybe we can reuse the types defined on the domain part

2023-01-17 15:08 UTC, lucacavallaro commented on packages/io-sign/src/__test__/document.spec.ts
> +          E.chain(markAsReady("https://my.document.url", [], [])),
I think that (`[], []`) is a bit ugly and confusing, since they share their context and lifecycle they can be composed to form a singular value object

2023-01-17 15:42 UTC, grausof commented on packages/io-sign/src/document.ts
> +  formFields: t.array(
This information has the same value as pages. I will try to merge both information into one attribute!

2023-01-17 20:20 UTC, gunzip reviewed
better 👍

2023-01-17 20:20 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +      A.head
you can use `findFirst`

2023-01-17 20:20 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +      A.filter((field) => field.name === attributes.uniqueName),
ditto

2023-01-17 20:20 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +const validateSignatureField =
```suggestion
const isValidSignatureField =
```

2023-01-17 20:20 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +const validateSignatureFieldToBeCreated =
```suggestion
const isValidaSignatureFieldToBeCreated =
```

2023-01-17 20:20 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +      E.chain((isValid) =>
you can use `E.mapLeft` instead

2023-01-18 08:27 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +      E.chain((isValid) =>
`isValid` is a boolean and if it is `false` I have to return a `leftEither`. With `mapLeft` instead I lose control over `isValid`.

2023-01-18 08:31 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
I'm having trouble with unit tests. They run locally but the code review pipeline fails!

2023-01-18 08:33 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
can you share a link to the action where they fail?

2023-01-18 08:34 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
sure! https://github.com/pagopa/io-sign/actions/runs/3943288342

2023-01-18 08:38 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
I probably found the cause, by directly launching` yarn run code-review` the pipeline fails, instead if a `yarn workspaces foreach run test` is first launched then the code-review is successful! Sounds like a turbo issue!

2023-01-18 08:39 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
using "turbo run typecheck lint test" locally ?

2023-01-18 08:41 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
i get the same pipeline error! If I then run `yarn workspaces foreach run test`, `turbo run typecheck lint test` works

2023-01-18 09:36 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
This is the error I get when I run the test locally the first time. The strange thing is that if I rerun the test no errors are returned. To reproduce it I had to use the `yarn jest --clearCache` command!

```
src/app/use-cases/validate-upload.ts:108:7 - error TS2345: Argument of type '<A>(ta: HKT<"Either", A>[]) => HKT<"Either", A[]>' is not assignable to parameter of type '(c: Either<string, boolean>[]) => HKT<"Either", unknown[]>'.
      Types of parameters 'ta' and 'c' are incompatible.
        Type 'Either<string, boolean>[]' is not assignable to type 'HKT<"Either", unknown>[]'.
          Type 'Either<string, boolean>' is not assignable to type 'HKT<"Either", unknown>'.
            Type 'Left<string>' is missing the following properties from type 'HKT<"Either", unknown>': _URI, _A

    108       A.sequence(applicativeValidation)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/app/use-cases/validate-upload.ts:138:9 - error TS2322: Type 'unknown' is not assignable to type 'TaskEither<Error, unknown>'.

    138         pipe(
                ~~~~~
    139           sequenceS(TE.ApplySeq)({
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ... 
    213           )
        ~~~~~~~~~~~
    214         )
        ~~~~~~~~~
```

2023-01-18 10:26 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
[This](https://github.com/devexperts/remote-data-ts/issues/49) looks like a similar problem but I can't figure it out! @gunzip

2023-01-18 15:59 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
I replaced `jest` with `vitest` which fixed the problem as it looks like a `jest` build problem that only happens in this particular repo setup.

2023-01-18 16:17 UTC, gunzip commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
@lucacavallaro do you see any issue using vitest instead of jest? (we must add an ADR in case pointing to this PR) of course with another PR

2023-01-18 17:27 UTC, grausof commented on apps/io-func-sign-issuer/src/app/use-cases/validate-upload.ts
> +                  ? E.right(true)
Please check #67

2023-01-23 10:00 UTC, lucacavallaro approved these changes

2023-01-23 11:35 UTC, gunzip approved these changes

2023-01-23 11:44 UTC, merged