feat: [SFEQS-1404] Implement endpoints to use messages with attachments
pagopa/io-sign pull request #78
Opened 2023-02-16 16:18 UTC by grausof

This PR implements the 2 endpoints needed to use messages with attachments.

In particular, the following endpoints have been implemented:
- `/messages/{signatureRequestId}` which allows you to obtain the list of documents (attachments) associated with a signature request.
- `/messages/{signatureRequestId}/{documentId}` Which allows you to obtain the content of the single document in the `application/pdf` format

#### How Has This Been Tested?
Tested locally with cloud resources

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-02-16 17:20 UTC, lucacavallaro requested changes

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/get-signed-document-content.ts
> +  );
this logic should be placed at the `domain` level

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/get-signed-document-content.ts
> +          A.findFirst((document) => document.id === documentId),
here you should use the `getDocument` function from the domain

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-attachments-content.ts
> +    })
the response should be constructed via the `handler-kit` utility functions

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/http/decoder/fiscal-code.ts
> +    header("fiscal_code"),
usually custom header names are prefixed (like `x-io-`) and written in `kebab-case` :'( 

if this choice does not depend on our system, maybe we can write a comment that explains the relation with external services

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/http/decoder/signature-request.ts
> +        // eslint-disable-next-line sonarjs/no-identical-functions
extract the function instead of disable `eslint`

2023-02-16 17:20 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/http/decoder/signature-request.ts
> +      fiscalCode: flow(requireFiscalCode),
```suggestion
      fiscalCode: requireFiscalCode,
```

2023-02-17 07:56 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/get-signed-document-content.ts
> +          A.findFirst((document) => document.id === documentId),
`getDocument` exist only in` io-func-sign-issuer`. I create it in `io-func-sign-user` as well

2023-02-17 07:58 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-attachments-content.ts
> +    })
Ok I add a dependency to the PR!

2023-02-17 08:00 UTC, grausof commented on apps/io-func-sign-user/src/infra/http/decoder/fiscal-code.ts
> +    header("fiscal_code"),
Unfortunately this choice does not depend on our system as specified [here](https://github.com/pagopa/io-backend/blob/c7257c946b99830fe8c052d4cc0d4dc78b000d51/openapi/consumed/api-third-party.yaml#L94). I add a comment!

2023-02-17 08:06 UTC, grausof commented on apps/io-func-sign-user/src/infra/http/decoder/signature-request.ts
> +      fiscalCode: flow(requireFiscalCode),
🫢

2023-02-17 08:39 UTC, grausof commented on apps/io-func-sign-user/src/infra/azure/functions/get-third-party-message-attachments-content.ts
> +    })
I checked the `handler-kit `code better and it is general purpose so it can already support raw type responses as well. I try to move this logic into `@io-sign` like `success` -> `jsonResponse`

2023-02-17 08:53 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/get-signed-document-content.ts
> +          A.findFirst((document) => document.id === documentId),
Move it to '@io-sign/sign'

2023-02-17 11:30 UTC, gunzip approved these changes

2023-02-17 11:30 UTC, gunzip commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
What about making this parametric (taken from a configuration object?)

2023-02-17 13:12 UTC, grausof commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
How about if we use an `envvar` to set the number of days for a signing request to be valid?

2023-02-17 13:17 UTC, gunzip commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
yes, env var is ok, but you can only access it at top level or from the configuration object (not directly inside this method)

2023-02-17 13:25 UTC, grausof commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
ok then I make sure that this value is read from a configuration, but instead of an `envvar` I insert it hard-coded in the [main](https://github.com/pagopa/io-sign/blob/main/apps/io-func-sign-user/src/app/main.ts) as done for other parameters (such as the names of the collections)

2023-02-17 13:25 UTC, lucacavallaro commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
imho this should not be an `env variable`, it's a simple "domain invariant" for the signature request entity

If we think it should change over time it is better to track it on the database

2023-02-17 13:27 UTC, grausof commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
@lucacavallaro what do you think about putting this invariant in `main.ts`?

2023-02-17 13:48 UTC, lucacavallaro commented on apps/io-func-sign-user/src/signature-request.ts
> +          difference < 90
ok let's leave it as it is now without changes, if in the future we need to change it we will understand why, how and any implications

2023-02-17 13:50 UTC, lucacavallaro approved these changes

2023-02-17 13:56 UTC, merged