chore: [SFEQS-1419] Update signed message to support third party content
pagopa/io-sign pull request #81
Opened 2023-02-20 17:41 UTC by grausof

This PR adds support for `third party content` and modifies the `message` of successful signature.

#### List of Changes
- Added `third_party_data` as an optional parameter in `@io-sign/io-sign/notification`
- Updated message of successful signature

#### How Has This Been Tested?
Tested locally with cloud resources

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-02-20 21:00 UTC, gunzip commented on packages/io-sign/src/infra/io-services/message.ts
> +                 * in any case we are enabled to use the attachments feature.
how?

2023-02-20 23:06 UTC, lucacavallaro requested changes

2023-02-21 07:21 UTC, gunzip commented on packages/io-sign/src/infra/io-services/message.ts
> +                 * in any case we are enabled to use the attachments feature.
I'd add this to the comment

2023-02-21 08:57 UTC, grausof commented on packages/io-sign/src/notification.ts
> +]);
Yes, I was thinking about doing a refactor like this. And then maybe with an encoder on the infra side. I proceed and ask you for a review!

2023-02-21 10:45 UTC, gunzip commented on packages/io-sign/src/infra/io-services/message.ts
> +        "signatureRequestId" in message
What about having two different encoders instead? 
(`NotificationContent` vs `NotificationContentWithAttachments`)

2023-02-21 10:50 UTC, grausof commented on packages/io-sign/src/infra/io-services/message.ts
> +        "signatureRequestId" in message
Done! it's a good idea!

2023-02-21 10:53 UTC, gunzip commented on packages/io-sign/src/notification.ts
> +export type NotificationMessage =
if you use a io-ts union instead you can call `NotificationMessage.encode` without first checking for the `signatureId`.

2023-02-21 11:02 UTC, grausof commented on packages/io-sign/src/notification.ts
> +export type NotificationMessage =
It's not clear to me. How do I define more than one encoder for the same type? NotificationMessage is part of the io-sign domain

2023-02-21 11:05 UTC, gunzip commented on packages/io-sign/src/notification.ts
> +export type NotificationMessage =
you're right sorry :-)

2023-02-21 16:01 UTC, lucacavallaro approved these changes

2023-02-21 16:14 UTC, merged