feat: [SFEQS-1345] Create selfcare thanks you page
pagopa/io-sign pull request #86
Opened 2023-02-27 15:47 UTC by grausof

This PR creates the frontend page for [selfcare](https://selfcare.pagopa.it/) with a temporary **thanks-you page** that will be used before the dev-portal is implemented.
This frontend is using [Next.js](https://nextjs.org/) and [mui-italia](https://github.com/pagopa/mui-italia) theme.

#### List of Changes
- Updated README
- Created new app in `apps/io-sign-selfcare-frontend` with **single index page**
- Added i18 support (as required by some components)
- Updated labeler pipeline

#### Motivation and Context

Before the **Firma con IO portal** for self-care is developed, it is necessary to show a temporary thanks you page to the institutions that carry out the onboarding.

#### How Has This Been Tested?
tested locally with `yarn dev` and then deployed on azure web sites.

#### Screenshots (if appropriate):
[PREVIEW HERE](https://gray-bay-0f6971f03-preview.westeurope.2.azurestaticapps.net/)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-02-27 16:53 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  /** The function to be invoked when pressing the rendered logout button, if not defined it will redirect to the logout page, if setted to null it will no render the logout button. It's possible to
```suggestion
  /** The function that will be called when the rendered logout button is pressed; if undefined, no logout button will be rendered; otherwise, it will redirect to the logout page on click. The logout path can be changed by altering the value in `CONFIG.logout` located inside the `index.tsx` file. */
```

I suggest to use https://quillbot.com/ for complex comments

2023-02-27 16:53 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  enableLogin?: boolean;
undefined and false have the same effect?

2023-02-27 16:53 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/static.ts
> +export const getI18nPaths = () =>
can you add a comment on what this method is supposed to do?

2023-02-27 16:53 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/pages/index.tsx
> +    const defaultBrowserLanguage = pipe(
is looks like this is a constant, what about extracting this outside the component and useEffet?

2023-02-27 16:53 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/pages/index.tsx
> +      O.fold(() => defaultLocale, identity)
you can use `getOrElse()`

2023-02-27 17:02 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  /** The function to be invoked when pressing the rendered logout button, if not defined it will redirect to the logout page, if setted to null it will no render the logout button. It's possible to
Taken from [here](https://github.com/pagopa/selfcare-common-frontend/blob/main/src/lib/components/Header/Header.tsx)😐 
I fix!

2023-02-27 17:06 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  enableLogin?: boolean;
No, undefined and true have the same effect!

2023-02-27 17:13 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  enableLogin?: boolean;
I'd add this into a comment

2023-02-27 17:18 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/pages/index.tsx
> +    const defaultBrowserLanguage = pipe(
`navigator.languages` is only available in `useEffect`!

2023-02-27 17:37 UTC, lucacavallaro requested changes

2023-02-27 17:37 UTC, lucacavallaro commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  /** The logged user or false if there is not a valid session */
Are these comments really needed?

2023-02-27 17:37 UTC, lucacavallaro commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  loggedUser: JwtUser | false;
why `false` and not `undefined` ?

2023-02-27 17:37 UTC, lucacavallaro commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  assistanceEmail: string;
- maybe we should use `support` instead of `assistance`
- why it's a `string`? it should be a `EmailString` from `ts-commons`

2023-02-27 17:37 UTC, lucacavallaro commented on apps/io-sign-selfcare-frontend/src/config.ts
> +export const CONFIG = {
why are the properties all in upper case?

2023-02-27 17:37 UTC, lucacavallaro commented on apps/io-sign-selfcare-frontend/src/pages/index.tsx
> +    Router.push("/" + defaultBrowserLanguage);
`fp-ts` here it is really needed?

2023-02-27 18:46 UTC, gunzip commented on apps/io-sign-selfcare-frontend/src/static.ts
> +//  Indicate which paths should be created on build time (returning a paths array) without fallback.
```suggestion
//  Indicate which paths should be created at build time (returning a paths array) without a fallback.
```

2023-02-28 08:27 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  /** The logged user or false if there is not a valid session */
these comments stem from [here](https://github.com/pagopa/selfcare-common-frontend/blob/main/src/lib/components/Header/Header.tsx)

2023-02-28 08:29 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  loggedUser: JwtUser | false;
This is expected by [mui-italia](https://main--633c31eff9fe385398ada426.chromatic.com/?path=/story/components-headeraccount-wip--logged-out )

2023-02-28 08:29 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/components/CommonHeader/CommonHeader.tsx
> +  assistanceEmail: string;
ditto!

2023-02-28 08:30 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/config.ts
> +export const CONFIG = {
These properties are common across projects, there is a [forum thread](https://github.com/pagopa/engineering/discussions/14) about them. Later this JSON will be provided via a CDN and this is the format used.

2023-02-28 08:31 UTC, grausof commented on apps/io-sign-selfcare-frontend/src/pages/index.tsx
> +    Router.push("/" + defaultBrowserLanguage);
Why not? This page is a WIP that will later become the developer portal and will certainly make use of fp-ts

2023-03-03 07:28 UTC, gunzip approved these changes

2023-03-03 12:53 UTC, merged