feat: [SFEQS-1463] Self-care integration
pagopa/io-sign pull request #87
Opened 2023-03-03 17:25 UTC by grausof

This PR adds self-care integration.

#### List of Changes

- Added `CreateIssuer` function triggered by selfcare event-hub
- Added `SelfCareEventHubConnectionString` to envvar
- Added `internalInstitutionId` parameter to `Issuer`
- Added connection to `self-care` eventhub for issuer creation after institution onboarding
- Fixed sending `internalInstitutionId` to `data-lake` for billing

#### Motivation and Context
With this PR, an issuer is created automatically as soon as the selfcare onoboarding ends.

#### How Has This Been Tested?
Tested locally with cloud resources and UAT selfcare event-hub

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +              query: `SELECT * FROM m WHERE m.${internalInstitutionIdKey} = @internalInstitutionIdKey`,
```suggestion
              query: `SELECT TOP 1 * FROM m WHERE m.${internalInstitutionIdKey} = @internalInstitutionIdKey`,
```

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
is this the partitionkey?

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/functions/create-issuer.ts
> +const makeValidateUploadHandler = (db: CosmosDatabase) => {
why "upload"? maybe a comment can help here

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/functions/create-issuer.ts
> +    // This is a fire-and-forget operation
are you sure you don't want to retry in case the insert operation fails?

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +              query: `SELECT * FROM m WHERE m.${internalInstitutionIdKey} = @internalInstitutionIdKey`,
I don't remember but maybe there's some cosmosdb method (on this) that you can use to get an item from its id.

2023-03-04 13:29 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/self-care/encoder.ts
> +    // See [IO-SIGN-RFC-SUB-ID]
can you elaborate this comment a little bit more? (what's happening here?)

2023-03-06 08:38 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
No, this is the parameter to look up!

2023-03-06 08:39 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/functions/create-issuer.ts
> +const makeValidateUploadHandler = (db: CosmosDatabase) => {
it's a typo!

2023-03-06 08:41 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/functions/create-issuer.ts
> +    // This is a fire-and-forget operation
The insert operation could fail only in case the DB is not responding. We should be able to figure out the type of error to perform a retry. Maybe I'll add a TODO

2023-03-06 08:42 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +              query: `SELECT * FROM m WHERE m.${internalInstitutionIdKey} = @internalInstitutionIdKey`,
Here we don't have to get an item from the id but from a parameter so i think the query is needed.

2023-03-07 09:23 UTC, gunzip requested changes

2023-03-07 09:23 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
yu must include the partition key in every query

2023-03-07 09:23 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/functions/create-issuer.ts
> +    // This is a fire-and-forget operation
yes, every IO operation that could fail (ie. db not responding) must be retried, that's why you must make your handler idempotent.

2023-03-07 09:28 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
In this case we do not know the `partitionKey` as the selfCare issuer id is contained only in the `internalInstitutionId` field. Therefore, a full table scan is required to understand if an entity already exists.

2023-03-07 09:30 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
this is a problem. when you omit the partition key every partition will be queried, so if you have 10 partitions, this means 10 different http calls to cosmosdb. you probably want to use just one partition if the table is small (I think this is doable someway with cosmos)

2023-03-07 09:33 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
A simple idea could be to use the same selfCare ID (`internalInstitutionId`) also for the issuer ID. In this way we don't have insertion problems as the id will be unique. In my opinion, having an `issuerId` and an `internalInstitutionId` makes no sense as there cannot be an institution with the same issuerId and a different internalInstitutionId.

2023-03-07 09:35 UTC, grausof commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +                  name: "@internalInstitutionIdKey",
[here](https://github.com/pagopa/io-sign/blob/607dbc7b564352b03610458d5dbe580d95c7c38d/apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts#L73)  too there is the same problem

2023-03-15 17:12 UTC, gunzip commented on apps/io-func-sign-issuer/src/infra/azure/cosmos/issuer.ts
> +      TE.chain(
maybe `chainOptionK` can help?

2023-03-16 09:04 UTC, lucacavallaro approved these changes

2023-03-16 09:22 UTC, merged