feat(user): [SFEQS-1478,SFEQS-1479]  Lollipop integration to `createSignature` endpoint 🍭
pagopa/io-sign pull request #94
Opened 2023-03-13 14:37 UTC by grausof

This PR adds lollipop implementation on the `createSignature` endpoint inside `io-func-sign-user`

#### List of Changes
- Added headers required by lollipop to `createSignature`
- Added lollipop infrastructure for API access
- Added SPID assertion retrieval via lollipop API
- Implemented forwarding of parameters to QTSP

#### How Has This Been Tested?
Tested locally

#### Checklist:
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-03-13 14:53 UTC, lucacavallaro commented on apps/io-func-sign-user/src/app/use-cases/create-signature.ts
> +        ).toString("base64") as NonEmptyString,
I think it's better to do a runtime validation (`validate(NonEmptyString)`) against the result of `Buffer.from`

2023-03-13 16:13 UTC, gunzip requested changes

2023-03-13 16:13 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +export const getSignatureFromHeaderName = (
this method needs unit tests

2023-03-13 16:15 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +export const getSignatureFromHeaderName = (
Are [here](https://github.com/pagopa/io-sign/pull/94/files#diff-4692cabafede767ad3fed30fac381c926511b8273864c7b0f7aed36f14147f7eR1)

2023-03-14 08:18 UTC, grausof commented on apps/io-func-sign-user/src/app/use-cases/create-signature.ts
> +        ).toString("base64") as NonEmptyString,
Ok I added validation on both `signatureInput` and `samlAssertion`

2023-03-14 08:19 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    RA.filterMapWithIndex((index: number, signatureInput: string) =>
done!

2023-03-14 08:35 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/http/decoder/lollipop.ts
> +        E.map((createSignatureLollipopParams) => ({
can you annotate here the static type that you expect after this map?

2023-03-14 08:41 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    /* signatureInput field contains the parameters of all the signatures (sig1, sig2, ...) separated by comma
What I meant was: describe each passage (in its own comment). ie. 

// Given a signature input: sig1=("FooBar"),sig2=("DeadBeef")
// and the header name: FooBar
// return the signature prefix with index: sig1
...

// Given a signature string: sig1=SomeValue;sig2=SomeOtherValue
// and the signature prefix with index: sig1
// extract the value part: SomeValue
...

// Given the signature value: SomeValue
// .. I don't know what's happening with S.split(/[::]/)
...

2023-03-14 08:44 UTC, gunzip requested changes

2023-03-14 08:44 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    /* signatureInput field contains the parameters of all the signatures (sig1, sig2, ...) separated by comma
I suspect that the corret regex is 

`new RegExp(`${signaturePrefix}:([^:])+`);`

2023-03-14 08:51 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    /* signatureInput field contains the parameters of all the signatures (sig1, sig2, ...) separated by comma
`new RegExp("sig1=:([^:]+)").exec("sig1=:asdsad:")[1]`

2023-03-14 09:04 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    /* signatureInput field contains the parameters of all the signatures (sig1, sig2, ...) separated by comma
Ok, I probably wasn't clear. I've tried reducing the code by adding a group to the regex. I hope with the added comments the flow is clearer now.

2023-03-14 09:06 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    /* signatureInput field contains the parameters of all the signatures (sig1, sig2, ...) separated by comma
https://regex101.com/r/dYceap/1

2023-03-14 09:08 UTC, gunzip requested changes

2023-03-14 09:08 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +  new RegExp(`${signaturePrefix}:([^:]*):?`);
```suggestion
  new RegExp(`${signaturePrefix}:([^:]+)`);
```

2023-03-14 09:08 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
you don't need chain + filterWithIndex, just use `A.lookup(1)`

2023-03-14 09:08 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    ),
```suggestion
        RA.lookup(1),
```

2023-03-14 09:11 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +  new RegExp(`${signaturePrefix}:([^:]*):?`);
Thanks! 
Regex ninja 🥷

2023-03-14 09:19 UTC, gunzip requested changes

2023-03-14 09:19 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
describe the supposed result with an example, not the implementation which is auto-evident

2023-03-14 09:19 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // extract a regex match: [sig1=:SomeValue:, SomeValue]
```suggestion
    // extract the value part: SomeValue
```

2023-03-14 09:22 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // extract a regex match: [sig1=:SomeValue:, SomeValue]
Ok, but I had to move` RA.lookup(1)` after `O.fromNullable`

2023-03-14 09:24 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
couldn't tests be used as examples?

2023-03-14 09:25 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
@lucacavallaro I think the aim is to explain step by step what happens and not the final result!

2023-03-14 09:26 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
it helps (even: code reviews) to co-locate comments, tests are about the whole implementation, here we describe each step. I'd to reverse engineer the code (and regex) to understand what's happening and make some contribution.

2023-03-14 09:28 UTC, lucacavallaro commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
the whole implementation could be split into several (single responsibility) functions, which can be unit-tested individually if it helps to have better clarity

2023-03-14 09:33 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
I think in this particular case maybe just add a unit-test just on the regex!

2023-03-14 10:13 UTC, grausof commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +    // Given the regex result extracts the first group: SomeValue
I split the `getSignatureFromHeaderName` function into 2 other functions (`getSignaturePrefixFromHeaderName`, `getSignatureFromPrefix`) and for each one I added a unit-test. I also defined the `LollipopSignaturePrefix` type for additional validation.

2023-03-14 10:16 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +      getSignRegexFromSignaturePrefix(signaturePrefix),
just inline the regex here

2023-03-14 10:16 UTC, gunzip commented on apps/io-func-sign-user/src/infra/lollipop/signature.ts
> +export const getSignaturePrefixFromHeaderName =
you can do this with a regex as well, something like

```
const getSignaturePrefix = (signatureInput: string) => (headerName: string) =>
  pipe(
    new RegExp('(sig[0-9]+=)\\("' + headerName + '"\\)').exec(signatureInput),
    O.fromNullable,
    O.chain(RA.lookup(1))
  );

```

2023-03-14 13:53 UTC, merged